#!/bin/sh

. /env/data/config

if [ -n "$CONFIG_ARM" ]; then
        supportgroup="#armlinux"
elif [ -n "$CONFIG_RISCV" ]; then
        supportgroup="#riscv"
elif [ -n "$CONFIG_OPENRISC" ]; then
        supportgroup="#openrisc"
fi

if [ -n "$supportgroup" ]; then
        readline "Want to ask for support on $supportgroup? [N/y]  " linuxsupport || linuxsupport="n"
fi

if [ "$linuxsupport" = "Y" ] || [ "$linuxsupport" = "y" ]; then
        supportgroup="#barebox"
fi

irc -n $global.user -c "/j $supportgroup" irc.libera.chat
